name: Terraform CI/CD Pipeline for github workflows

on:
  push:
    branches:
      - main

env:
  TERRAFORM_VERSION: '1.5.0'
  RESOURCE_GROUP_NAME: 'my-rg-tf-01'
  LOCATION: 'eastus'
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Format Check
        working-directory: IaC/Terraform
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: IaC/Terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: IaC/Terraform
        run: terraform validate

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: IaC/Terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: IaC/Terraform
        run: |
          terraform plan -out=tfplan \
            -var="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" \
            -var="location=${{ env.LOCATION }}" \
            -var="azure_client_id=${{ env.AZURE_CLIENT_ID }}" \
            -var="azure_client_secret=${{ env.AZURE_CLIENT_SECRET }}" \
            -var="azure_tenant_id=${{ env.AZURE_TENANT_ID }}" \
            -var="subscription_id=${{ env.AZURE_SUBSCRIPTION_ID }}"

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: IaC/Terraform/tfplan
          retention-days: 1

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: IaC/Terraform

      - name: Terraform Init
        working-directory: IaC/Terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: IaC/Terraform
        run: terraform apply -auto-approve tfplan